server:
  port: 6888

spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Projects/device-ms-demo-config

eureka:

  instance:
    hostname: configserver

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/